# Generated by Django 5.2 on 2025-05-01 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milksale',
            name='price_per_liter',
        ),
        migrations.AlterField(
            model_name='milksale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
