# Generated by Django 5.2 on 2025-05-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_health', '0003_remove_deworming_deworming_product'),
        ('milk_tracking', '0002_remove_milksale_price_per_liter_alter_milksale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_productions', to='animal_health.cow')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cow', 'date')},
            },
        ),
    ]
