# Generated by Django 5.2 on 2025-05-01 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=100, unique=True)),
                ('breed', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deworming_product', models.CharField(max_length=100)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_health.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Steaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_health.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vaccine_name', models.CharField(max_length=100)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_health.cow')),
            ],
        ),
    ]
