# Generated by Django 5.2 on 2025-05-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='tag_number',
            new_name='name',
        ),
    ]
