# Generated by Django 5.2 on 2025-05-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_health', '0002_rename_tag_number_cow_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deworming',
            name='deworming_product',
        ),
    ]
