# Generated by Django 5.2 on 2025-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Feed', 'Feed'), ('Labor', 'Labor'), ('Veterinary', 'Veterinary'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
